inherit_from: .rubocop_todo.yml

# Style/Encoding:
#   Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 30
  
Documentation:
  Enabled: false